# .github/workflows/ci_cd.yml

name: CI Pipeline

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - uses: iterative/setup-cml@v2
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run main file
      run: |
        python main.py
    
    - name: Run Tests
      run: |
        python -m unittest discover

    - name: Create CML report
      env:
        REPO_TOKEN: ${{ secrets.TOKEN }}
      run: |

        echo "# First Line of our report" > README.md
        echo "## Bar Plots" >> README.md
        echo '![](./bars.png "Bar plot")' >> README.md
        echo "## Line Plots" >> README.md
        echo '![](./lines.png "Line plot")' >> README.md

        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add README.md
        git commit -m "Auto-update README from CI"
        git push

        cml comment create README.md